config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :path => '', :path_names => {:sign_up => 'register', :sign_in => 'login', :sign_out => 'logout'}
  root 'teams#index'
  resources :jerseys
  resources :organization_teams
  resources :organizations
  resources :teams
  resources :person_email_addresses
  resources :person_phones
  resources :person_postal_addresses
  resources :email_addresses
  resources :phones
  resources :postal_addresses
  resources :people
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/email_address.rb
class EmailAddress < ApplicationRecord
end

app/models/jersey.rb
class Jersey < ApplicationRecord
  belongs_to :person
  belongs_to :team
end

app/models/organization.rb
class Organization < ApplicationRecord
end

app/models/organization_team.rb
class OrganizationTeam < ApplicationRecord
  belongs_to :organization
  belongs_to :team
end

app/models/person.rb
class Person < ApplicationRecord
  rolify
end

app/models/person_email_address.rb
class PersonEmailAddress < ApplicationRecord
  belongs_to :person
  belongs_to :email_address
end

app/models/person_phone.rb
class PersonPhone < ApplicationRecord
  belongs_to :person
  belongs_to :phone
end

app/models/person_postal_address.rb
class PersonPostalAddress < ApplicationRecord
  belongs_to :person
  belongs_to :postal_address
end

app/models/phone.rb
class Phone < ApplicationRecord
end

app/models/postal_address.rb
class PostalAddress < ApplicationRecord
end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :people, :join_table => :people_roles

  belongs_to :resource,
             :polymorphic => true,
             :optional => true

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/team.rb
class Team < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/person_phones_controller.rb
class PersonPhonesController < ApplicationController
  before_action :set_person_phone, only: [:show, :edit, :update, :destroy]

  # GET /person_phones
  # GET /person_phones.json
  def index
    @person_phones = PersonPhone.all
  end

  # GET /person_phones/1
  # GET /person_phones/1.json
  def show
  end

  # GET /person_phones/new
  def new
    @person_phone = PersonPhone.new
  end

  # GET /person_phones/1/edit
  def edit
  end

  # POST /person_phones
  # POST /person_phones.json
  def create
    @person_phone = PersonPhone.new(person_phone_params)

    respond_to do |format|
      if @person_phone.save
        format.html { redirect_to @person_phone, notice: 'Person phone was successfully created.' }
        format.json { render :show, status: :created, location: @person_phone }
      else
        format.html { render :new }
        format.json { render json: @person_phone.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /person_phones/1
  # PATCH/PUT /person_phones/1.json
  def update
    respond_to do |format|
      if @person_phone.update(person_phone_params)
        format.html { redirect_to @person_phone, notice: 'Person phone was successfully updated.' }
        format.json { render :show, status: :ok, location: @person_phone }
      else
        format.html { render :edit }
        format.json { render json: @person_phone.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /person_phones/1
  # DELETE /person_phones/1.json
  def destroy
    @person_phone.destroy
    respond_to do |format|
      format.html { redirect_to person_phones_url, notice: 'Person phone was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_person_phone
      @person_phone = PersonPhone.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def person_phone_params
      params.require(:person_phone).permit(:person_id, :phone_id)
    end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  before_action :set_team, only: [:show, :edit, :update, :destroy]

  # GET /teams
  # GET /teams.json
  def index
    @teams = Team.all
  end

  # GET /teams/1
  # GET /teams/1.json
  def show
  end

  # GET /teams/new
  def new
    @team = Team.new
  end

  # GET /teams/1/edit
  def edit
  end

  # POST /teams
  # POST /teams.json
  def create
    @team = Team.new(team_params)

    respond_to do |format|
      if @team.save
        format.html { redirect_to @team, notice: 'Team was successfully created.' }
        format.json { render :show, status: :created, location: @team }
      else
        format.html { render :new }
        format.json { render json: @team.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /teams/1
  # PATCH/PUT /teams/1.json
  def update
    respond_to do |format|
      if @team.update(team_params)
        format.html { redirect_to @team, notice: 'Team was successfully updated.' }
        format.json { render :show, status: :ok, location: @team }
      else
        format.html { render :edit }
        format.json { render json: @team.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /teams/1
  # DELETE /teams/1.json
  def destroy
    @team.destroy
    respond_to do |format|
      format.html { redirect_to teams_url, notice: 'Team was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_team
      @team = Team.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def team_params
      params.require(:team).permit(:name, :age_group)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/jerseys_helper.rb
module JerseysHelper
end

app/helpers/organizations_helper.rb
module OrganizationsHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/person_phones_helper.rb
module PersonPhonesHelper
end

app/helpers/phones_helper.rb
module PhonesHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/views/person_phones/_form.html.erb
<%= form_for(person_phone) do |f| %>
  <% if person_phone.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(person_phone.errors.count, "error") %> prohibited this person_phone from being saved:</h2>

      <ul>
      <% person_phone.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :person_id %>
    <%= f.text_field :person_id %>
  </div>

  <div class="field">
    <%= f.label :phone_id %>
    <%= f.text_field :phone_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/person_phones/edit.html.erb
<h1>Editing Person Phone</h1>

<%= render 'form', person_phone: @person_phone %>

<%= link_to 'Show', @person_phone %> |
<%= link_to 'Back', person_phones_path %>

app/views/person_phones/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Person Phones</h1>

<table>
  <thead>
    <tr>
      <th>Person</th>
      <th>Phone</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @person_phones.each do |person_phone| %>
      <tr>
        <td><%= person_phone.person %></td>
        <td><%= person_phone.phone %></td>
        <td><%= link_to 'Show', person_phone %></td>
        <td><%= link_to 'Edit', edit_person_phone_path(person_phone) %></td>
        <td><%= link_to 'Destroy', person_phone, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Person Phone', new_person_phone_path %>

app/views/person_phones/new.html.erb
<h1>New Person Phone</h1>

<%= render 'form', person_phone: @person_phone %>

<%= link_to 'Back', person_phones_path %>

app/views/person_phones/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Person:</strong>
  <%= @person_phone.person %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @person_phone.phone %>
</p>

<%= link_to 'Edit', edit_person_phone_path(@person_phone) %> |
<%= link_to 'Back', person_phones_path %>