config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :path => '', :path_names => {:sign_up => 'register', :sign_in => 'login', :sign_out => 'logout'}
  root 'teams#index'
  resources :jerseys
  resources :organization_teams
  resources :organizations
  resources :teams
  resources :person_email_addresses
  resources :person_phones
  resources :person_postal_addresses
  resources :email_addresses
  resources :phones
  resources :postal_addresses
  resources :people
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/email_address.rb
class EmailAddress < ApplicationRecord
end

app/models/jersey.rb
class Jersey < ApplicationRecord
  belongs_to :person
  belongs_to :team
end

app/models/organization.rb
class Organization < ApplicationRecord
end

app/models/organization_team.rb
class OrganizationTeam < ApplicationRecord
  belongs_to :organization
  belongs_to :team
end

app/models/person.rb
class Person < ApplicationRecord
  rolify
end

app/models/person_email_address.rb
class PersonEmailAddress < ApplicationRecord
  belongs_to :person
  belongs_to :email_address
end

app/models/person_phone.rb
class PersonPhone < ApplicationRecord
  belongs_to :person
  belongs_to :phone
end

app/models/phone.rb
class Phone < ApplicationRecord
end

app/models/postal_address.rb
class PostalAddress < ApplicationRecord
end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :people, :join_table => :people_roles

  belongs_to :resource,
             :polymorphic => true,
             :optional => true

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/team.rb
class Team < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/postal_addresses_controller.rb
class PostalAddressesController < ApplicationController
  before_action :set_postal_address, only: [:show, :edit, :update, :destroy]

  # GET /postal_addresses
  # GET /postal_addresses.json
  def index
    @postal_addresses = PostalAddress.all
  end

  # GET /postal_addresses/1
  # GET /postal_addresses/1.json
  def show
  end

  # GET /postal_addresses/new
  def new
    @postal_address = PostalAddress.new
  end

  # GET /postal_addresses/1/edit
  def edit
  end

  # POST /postal_addresses
  # POST /postal_addresses.json
  def create
    @postal_address = PostalAddress.new(postal_address_params)

    respond_to do |format|
      if @postal_address.save
        format.html { redirect_to @postal_address, notice: 'Postal address was successfully created.' }
        format.json { render :show, status: :created, location: @postal_address }
      else
        format.html { render :new }
        format.json { render json: @postal_address.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /postal_addresses/1
  # PATCH/PUT /postal_addresses/1.json
  def update
    respond_to do |format|
      if @postal_address.update(postal_address_params)
        format.html { redirect_to @postal_address, notice: 'Postal address was successfully updated.' }
        format.json { render :show, status: :ok, location: @postal_address }
      else
        format.html { render :edit }
        format.json { render json: @postal_address.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /postal_addresses/1
  # DELETE /postal_addresses/1.json
  def destroy
    @postal_address.destroy
    respond_to do |format|
      format.html { redirect_to postal_addresses_url, notice: 'Postal address was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_postal_address
      @postal_address = PostalAddress.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def postal_address_params
      params.require(:postal_address).permit(:street_line_1, :street_line_2, :city, :state, :zip)
    end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  before_action :set_team, only: [:show, :edit, :update, :destroy]

  # GET /teams
  # GET /teams.json
  def index
    @teams = Team.all
  end

  # GET /teams/1
  # GET /teams/1.json
  def show
  end

  # GET /teams/new
  def new
    @team = Team.new
  end

  # GET /teams/1/edit
  def edit
  end

  # POST /teams
  # POST /teams.json
  def create
    @team = Team.new(team_params)

    respond_to do |format|
      if @team.save
        format.html { redirect_to @team, notice: 'Team was successfully created.' }
        format.json { render :show, status: :created, location: @team }
      else
        format.html { render :new }
        format.json { render json: @team.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /teams/1
  # PATCH/PUT /teams/1.json
  def update
    respond_to do |format|
      if @team.update(team_params)
        format.html { redirect_to @team, notice: 'Team was successfully updated.' }
        format.json { render :show, status: :ok, location: @team }
      else
        format.html { render :edit }
        format.json { render json: @team.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /teams/1
  # DELETE /teams/1.json
  def destroy
    @team.destroy
    respond_to do |format|
      format.html { redirect_to teams_url, notice: 'Team was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_team
      @team = Team.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def team_params
      params.require(:team).permit(:name, :age_group)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/jerseys_helper.rb
module JerseysHelper
end

app/helpers/organizations_helper.rb
module OrganizationsHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/phones_helper.rb
module PhonesHelper
end

app/helpers/postal_addresses_helper.rb
module PostalAddressesHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/views/postal_addresses/_form.html.erb
<%= form_for(postal_address) do |f| %>
  <% if postal_address.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(postal_address.errors.count, "error") %> prohibited this postal_address from being saved:</h2>

      <ul>
      <% postal_address.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :street_line_1 %>
    <%= f.text_field :street_line_1 %>
  </div>

  <div class="field">
    <%= f.label :street_line_2 %>
    <%= f.text_field :street_line_2 %>
  </div>

  <div class="field">
    <%= f.label :city %>
    <%= f.text_field :city %>
  </div>

  <div class="field">
    <%= f.label :state %>
    <%= f.text_field :state %>
  </div>

  <div class="field">
    <%= f.label :zip %>
    <%= f.text_field :zip %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/postal_addresses/edit.html.erb
<h1>Editing Postal Address</h1>

<%= render 'form', postal_address: @postal_address %>

<%= link_to 'Show', @postal_address %> |
<%= link_to 'Back', postal_addresses_path %>

app/views/postal_addresses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Postal Addresses</h1>

<table>
  <thead>
    <tr>
      <th>Street line 1</th>
      <th>Street line 2</th>
      <th>City</th>
      <th>State</th>
      <th>Zip</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @postal_addresses.each do |postal_address| %>
      <tr>
        <td><%= postal_address.street_line_1 %></td>
        <td><%= postal_address.street_line_2 %></td>
        <td><%= postal_address.city %></td>
        <td><%= postal_address.state %></td>
        <td><%= postal_address.zip %></td>
        <td><%= link_to 'Show', postal_address %></td>
        <td><%= link_to 'Edit', edit_postal_address_path(postal_address) %></td>
        <td><%= link_to 'Destroy', postal_address, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Postal Address', new_postal_address_path %>

app/views/postal_addresses/new.html.erb
<h1>New Postal Address</h1>

<%= render 'form', postal_address: @postal_address %>

<%= link_to 'Back', postal_addresses_path %>

app/views/postal_addresses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Street line 1:</strong>
  <%= @postal_address.street_line_1 %>
</p>

<p>
  <strong>Street line 2:</strong>
  <%= @postal_address.street_line_2 %>
</p>

<p>
  <strong>City:</strong>
  <%= @postal_address.city %>
</p>

<p>
  <strong>State:</strong>
  <%= @postal_address.state %>
</p>

<p>
  <strong>Zip:</strong>
  <%= @postal_address.zip %>
</p>

<%= link_to 'Edit', edit_postal_address_path(@postal_address) %> |
<%= link_to 'Back', postal_addresses_path %>