config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :path => '', :path_names => {:sign_up => 'register', :sign_in => 'login', :sign_out => 'logout'}
  root 'teams#index'
  resources :jerseys
  resources :organization_teams
  resources :organizations
  resources :teams
  resources :person_email_addresses
  resources :person_phones
  resources :person_postal_addresses
  resources :email_addresses
  resources :phones
  resources :postal_addresses
  resources :people
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/email_address.rb
class EmailAddress < ApplicationRecord
end

app/models/jersey.rb
class Jersey < ApplicationRecord
  belongs_to :person
  belongs_to :team
end

app/models/organization.rb
class Organization < ApplicationRecord
end

app/models/organization_team.rb
class OrganizationTeam < ApplicationRecord
  belongs_to :organization
  belongs_to :team
end

app/models/person.rb
class Person < ApplicationRecord
  rolify
end

app/models/person_email_address.rb
class PersonEmailAddress < ApplicationRecord
  belongs_to :person
  belongs_to :email_address
end

app/models/person_phone.rb
class PersonPhone < ApplicationRecord
  belongs_to :person
  belongs_to :phone
end

app/models/phone.rb
class Phone < ApplicationRecord
end

app/models/postal_address.rb
class PostalAddress < ApplicationRecord
end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :people, :join_table => :people_roles

  belongs_to :resource,
             :polymorphic => true,
             :optional => true

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/team.rb
class Team < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/organization_teams_controller.rb
class OrganizationTeamsController < ApplicationController
  before_action :set_organization_team, only: [:show, :edit, :update, :destroy]

  # GET /organization_teams
  # GET /organization_teams.json
  def index
    @organization_teams = OrganizationTeam.all
  end

  # GET /organization_teams/1
  # GET /organization_teams/1.json
  def show
  end

  # GET /organization_teams/new
  def new
    @organization_team = OrganizationTeam.new
  end

  # GET /organization_teams/1/edit
  def edit
  end

  # POST /organization_teams
  # POST /organization_teams.json
  def create
    @organization_team = OrganizationTeam.new(organization_team_params)

    respond_to do |format|
      if @organization_team.save
        format.html { redirect_to @organization_team, notice: 'Organization team was successfully created.' }
        format.json { render :show, status: :created, location: @organization_team }
      else
        format.html { render :new }
        format.json { render json: @organization_team.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /organization_teams/1
  # PATCH/PUT /organization_teams/1.json
  def update
    respond_to do |format|
      if @organization_team.update(organization_team_params)
        format.html { redirect_to @organization_team, notice: 'Organization team was successfully updated.' }
        format.json { render :show, status: :ok, location: @organization_team }
      else
        format.html { render :edit }
        format.json { render json: @organization_team.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /organization_teams/1
  # DELETE /organization_teams/1.json
  def destroy
    @organization_team.destroy
    respond_to do |format|
      format.html { redirect_to organization_teams_url, notice: 'Organization team was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_organization_team
      @organization_team = OrganizationTeam.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def organization_team_params
      params.require(:organization_team).permit(:organization_id, :team_id)
    end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  before_action :set_team, only: [:show, :edit, :update, :destroy]

  # GET /teams
  # GET /teams.json
  def index
    @teams = Team.all
  end

  # GET /teams/1
  # GET /teams/1.json
  def show
  end

  # GET /teams/new
  def new
    @team = Team.new
  end

  # GET /teams/1/edit
  def edit
  end

  # POST /teams
  # POST /teams.json
  def create
    @team = Team.new(team_params)

    respond_to do |format|
      if @team.save
        format.html { redirect_to @team, notice: 'Team was successfully created.' }
        format.json { render :show, status: :created, location: @team }
      else
        format.html { render :new }
        format.json { render json: @team.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /teams/1
  # PATCH/PUT /teams/1.json
  def update
    respond_to do |format|
      if @team.update(team_params)
        format.html { redirect_to @team, notice: 'Team was successfully updated.' }
        format.json { render :show, status: :ok, location: @team }
      else
        format.html { render :edit }
        format.json { render json: @team.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /teams/1
  # DELETE /teams/1.json
  def destroy
    @team.destroy
    respond_to do |format|
      format.html { redirect_to teams_url, notice: 'Team was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_team
      @team = Team.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def team_params
      params.require(:team).permit(:name, :age_group)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/jerseys_helper.rb
module JerseysHelper
end

app/helpers/organization_teams_helper.rb
module OrganizationTeamsHelper
end

app/helpers/organizations_helper.rb
module OrganizationsHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/person_phones_helper.rb
module PersonPhonesHelper
end

app/helpers/phones_helper.rb
module PhonesHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/views/organization_teams/_form.html.erb
<%= form_for(organization_team) do |f| %>
  <% if organization_team.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(organization_team.errors.count, "error") %> prohibited this organization_team from being saved:</h2>

      <ul>
      <% organization_team.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :organization_id %>
    <%= f.text_field :organization_id %>
  </div>

  <div class="field">
    <%= f.label :team_id %>
    <%= f.text_field :team_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/organization_teams/edit.html.erb
<h1>Editing Organization Team</h1>

<%= render 'form', organization_team: @organization_team %>

<%= link_to 'Show', @organization_team %> |
<%= link_to 'Back', organization_teams_path %>

app/views/organization_teams/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Organization Teams</h1>

<table>
  <thead>
    <tr>
      <th>Organization</th>
      <th>Team</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @organization_teams.each do |organization_team| %>
      <tr>
        <td><%= organization_team.organization %></td>
        <td><%= organization_team.team %></td>
        <td><%= link_to 'Show', organization_team %></td>
        <td><%= link_to 'Edit', edit_organization_team_path(organization_team) %></td>
        <td><%= link_to 'Destroy', organization_team, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Organization Team', new_organization_team_path %>

app/views/organization_teams/new.html.erb
<h1>New Organization Team</h1>

<%= render 'form', organization_team: @organization_team %>

<%= link_to 'Back', organization_teams_path %>

app/views/organization_teams/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Organization:</strong>
  <%= @organization_team.organization %>
</p>

<p>
  <strong>Team:</strong>
  <%= @organization_team.team %>
</p>

<%= link_to 'Edit', edit_organization_team_path(@organization_team) %> |
<%= link_to 'Back', organization_teams_path %>